# Generated by Django 5.2.8 on 2025-12-01 14:52

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=news.models.article_image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
