# Generated by Django 4.2 on 2025-09-26 19:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "pen_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de plume"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de décès"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Française", max_length=100, verbose_name="Nationalité"
                    ),
                ),
                ("biography", ckeditor.fields.RichTextField(verbose_name="Biographie")),
                (
                    "short_bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Biographie courte"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "social_media",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réseaux sociaux"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Auteur mis en avant"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
                "ordering": ["last_name", "first_name"],
                "unique_together": {("first_name", "last_name")},
            },
        ),
    ]
