# Generated by Django 4.2 on 2025-09-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="nationality",
        ),
    ]
