# Generated by Django 5.2.8 on 2025-12-01 14:52

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_remove_author_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=author.models.author_photo_upload_path,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=author.models.empty_dict,
                verbose_name="Réseaux sociaux",
            ),
        ),
    ]
