# Generated by Django 5.2.6 on 2025-11-01 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL Facebook",
                    ),
                ),
                (
                    "tiktok_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL TikTok",
                    ),
                ),
                (
                    "linkedin_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL LinkedIn",
                    ),
                ),
                (
                    "instagram_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL Instagram",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres des réseaux sociaux",
                "verbose_name_plural": "Paramètres des réseaux sociaux",
            },
        ),
    ]
