# Generated by Django 4.2 on 2025-09-27 07:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("author", "0002_remove_author_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Description courte"
                    ),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="Extrait")),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="Date de publication"),
                ),
                ("pages", models.PositiveIntegerField(verbose_name="Nombre de pages")),
                (
                    "language",
                    models.CharField(
                        default="Français", max_length=50, verbose_name="Langue"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("poche", "Poche"),
                            ("broche", "Broché"),
                            ("relié", "Relié"),
                            ("ebook", "E-book"),
                            ("audio", "Livre audio"),
                        ],
                        default="broche",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="books/covers/", verbose_name="Image de couverture"
                    ),
                ),
                (
                    "back_cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/backs/",
                        verbose_name="Image de quatrième de couverture",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Prix"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Prix de promotion",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en stock"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="Best-seller"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Description SEO"
                    ),
                ),
                ("keywords", models.TextField(blank=True, verbose_name="Mots-clés")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="author.author",
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="books/gallery/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texte alternatif"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Image principale"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.book",
                        verbose_name="Livre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de livre",
                "verbose_name_plural": "Images de livres",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="shop.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Note",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'avis"),
                ),
                ("comment", models.TextField(verbose_name="Commentaire")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-created_at"],
                "unique_together": {("book", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_available", "is_featured"],
                name="shop_book_is_avai_a6ae49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["category", "is_available"], name="shop_book_categor_9a1014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["author", "is_available"], name="shop_book_author__c28b8c_idx"
            ),
        ),
    ]
