# Generated by Django 5.2.6 on 2025-10-18 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_cart_user_cart_cart_has_user_or_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payée"),
                            ("failed", "Échouée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "shipping_first_name",
                    models.CharField(max_length=50, verbose_name="Prénom"),
                ),
                (
                    "shipping_last_name",
                    models.CharField(max_length=50, verbose_name="Nom"),
                ),
                ("shipping_address", models.TextField(verbose_name="Adresse")),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="Ville"),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "shipping_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "billing_first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prénom facturation"
                    ),
                ),
                (
                    "billing_last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nom facturation"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Adresse facturation"),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ville facturation"
                    ),
                ),
                (
                    "billing_postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Code postal facturation",
                    ),
                ),
                (
                    "billing_country",
                    models.CharField(
                        default="France",
                        max_length=100,
                        verbose_name="Pays facturation",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sous-total"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Frais de port",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Montant des taxes",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant total"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix total"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commande",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("bank_transfer", "Virement bancaire"),
                            ("check", "Chèque"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "paypal_payment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de paiement PayPal"
                    ),
                ),
                (
                    "paypal_payer_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID du payeur PayPal"
                    ),
                ),
                (
                    "paypal_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Token PayPal"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de finalisation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_has_user_or_session",
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="shop.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "book")},
        ),
    ]
