# Generated by Django 5.2.6 on 2025-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_orderitem_payment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=8,
                        verbose_name="Seuil de livraison gratuite (€)",
                    ),
                ),
                (
                    "standard_shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.9,
                        max_digits=8,
                        verbose_name="Coût de livraison standard (€)",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.5,
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        default="Éditions Sen",
                        max_length=200,
                        verbose_name="Nom de la boutique",
                    ),
                ),
                (
                    "shop_email",
                    models.EmailField(
                        default="contact@editions-sen.com",
                        max_length=254,
                        verbose_name="Email de la boutique",
                    ),
                ),
                (
                    "shop_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Téléphone de la boutique",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de la boutique",
                "verbose_name_plural": "Paramètres de la boutique",
            },
        ),
    ]
