# Generated by Django 4.2 on 2025-10-19 11:34

from django.db import migrations, models


def empty_dict():
    """Retourne un dictionnaire vide pour les valeurs par défaut JSONField"""
    return {}


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_loyaltyprogram_promocode_userloyaltystatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_data",
            field=models.JSONField(
                blank=True, default=empty_dict, verbose_name="Données de session"
            ),
        ),
    ]
