# Generated by Django 4.2 on 2025-10-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_cart_session_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de facturation"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(max_length=200, verbose_name="Nom de facturation"),
                ),
                (
                    "billing_address",
                    models.TextField(verbose_name="Adresse de facturation"),
                ),
                (
                    "billing_city",
                    models.CharField(max_length=100, verbose_name="Ville"),
                ),
                (
                    "billing_postal_code",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                (
                    "billing_country",
                    models.CharField(max_length=100, verbose_name="Pays"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sous-total"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Frais de port",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant total"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="shop.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-invoice_date"],
            },
        ),
    ]
