# Generated by Django 4.2 on 2025-10-19 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0009_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="actual_delivery",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de livraison effective"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Notes administrateur"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'annulation"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Transporteur"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de livraison"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de livraison estimée"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="processing_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de traitement"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'expédition"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro de suivi"
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="Ancien statut"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="Nouveau statut"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de changement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="shop.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut",
                "verbose_name_plural": "Historique des statuts",
                "ordering": ["-changed_at"],
            },
        ),
    ]
