# Generated by Django 4.2 on 2025-10-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_order_actual_delivery_order_admin_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyée"),
                    ("paid", "Payée"),
                    ("overdue", "En retard"),
                    ("cancelled", "Annulée"),
                ],
                default="sent",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
