# Generated by Django 5.2.6 on 2025-11-01 20:04

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_update_invoice_default_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_viewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de consultation par l'admin"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="back_cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shop.models.book_back_upload_path,
                verbose_name="Image de quatrième de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                upload_to=shop.models.book_cover_upload_path,
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="bookimage",
            name="image",
            field=models.ImageField(
                upload_to=shop.models.book_gallery_upload_path, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmée"),
                    ("processing", "En cours de traitement"),
                    ("shipped", "Expédiée"),
                    ("delivered", "Livrée"),
                    ("cancelled", "Annulée"),
                    ("refunded", "Remboursée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
