# Generated by Django 5.2.8 on 2025-11-21 20:27

from django.db import migrations, models


def migrate_author_to_authors(apps, schema_editor):
    """Migre les données de author (ForeignKey) vers authors (ManyToManyField)"""
    Book = apps.get_model('shop', 'Book')
    Author = apps.get_model('author', 'Author')
    
    # Pour chaque livre, ajouter son auteur dans la relation ManyToMany
    for book in Book.objects.all():
        # Récupérer l'auteur via l'ancien champ ForeignKey
        # Note: on accède à l'ancien champ via l'ID stocké dans la base
        if hasattr(book, 'author_id') and book.author_id:
            try:
                author = Author.objects.get(id=book.author_id)
                # Ajouter l'auteur à la relation ManyToMany
                book.authors.add(author)
            except Author.DoesNotExist:
                pass


def reverse_migrate_authors_to_author(apps, schema_editor):
    """Migration inverse : récupère le premier auteur de authors et le met dans author"""
    Book = apps.get_model('shop', 'Book')
    Author = apps.get_model('author', 'Author')
    
    # Pour chaque livre, prendre le premier auteur et le mettre dans author
    for book in Book.objects.all():
        authors = book.authors.all()
        if authors.exists():
            # Prendre le premier auteur
            first_author = authors.first()
            # Mettre à jour le champ author (qui sera recréé)
            book.author_id = first_author.id
            book.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_add_admin_viewed_at_to_order"),
        ("author", "0002_remove_author_nationality"),
    ]

    operations = [
        # Étape 1: Ajouter le nouveau champ ManyToManyField (temporairement nullable)
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books",
                to="author.author",
                verbose_name="Auteurs",
            ),
        ),
        # Étape 2: Migrer les données
        migrations.RunPython(migrate_author_to_authors, reverse_migrate_authors_to_author),
        # Étape 3: Supprimer l'ancien champ ForeignKey
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
