# Generated by Django 5.2.8 on 2025-11-23 12:28

import shop.models
from django.db import migrations, models


def remove_old_index_if_exists(apps, schema_editor):
    """Supprime l'ancien index s'il existe"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        try:
            # Vérifier si l'index existe
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' "
                "AND name='shop_book_author__c28b8c_idx'"
            )
            if cursor.fetchone():
                cursor.execute(
                    "DROP INDEX shop_book_author__c28b8c_idx"
                )
        except Exception:
            pass  # L'index n'existe pas, on continue


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_change_author_to_authors"),
    ]

    operations = [
        migrations.RunPython(remove_old_index_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name="book",
            name="is_preorder",
            field=models.BooleanField(default=False, verbose_name="En précommande"),
        ),
        migrations.AddField(
            model_name="book",
            name="preorder_available_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de disponibilité prévue"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="preorder_current_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de précommandes effectuées"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="preorder_max_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Quantité maximale de précommandes (None = illimité)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="preorder_original_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date originale de précommande"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_preorder",
            field=models.BooleanField(
                default=False, verbose_name="Commande de précommande"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="preorder_date_change_notified",
            field=models.BooleanField(
                default=False, verbose_name="Client notifié du changement de date"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="preorder_date_changed",
            field=models.BooleanField(
                default=False, verbose_name="Date de précommande modifiée"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="preorder_original_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date initiale promise pour la précommande",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="preorder_ready_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date où la précommande est devenue disponible",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_data",
            field=models.JSONField(
                blank=True,
                default=shop.models.empty_dict,
                verbose_name="Données de session",
            ),
        ),
    ]
