# Generated by Django 5.2.8 on 2025-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_remove_book_shop_book_author__c28b8c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(
                choices=[
                    ("poche", "Poche"),
                    ("broche", "Broché"),
                    ("relié", "Relié"),
                    ("ebook", "E-book"),
                    ("boxe", "Boxe"),
                    ("audio", "Livre audio"),
                ],
                default="broche",
                max_length=20,
                verbose_name="Format",
            ),
        ),
    ]
