# Generated by Django 5.2.6 on 2025-11-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_author_index_safely'),
    ]

    operations = [
    ]
