# Generated by Django 5.2.8 on 2025-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_book_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=20, verbose_name="ISBN"),
        ),
    ]
