# Generated by Django 5.2.6 on 2025-11-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_preorder_fields'),
        ('shop', '0017_remove_author_index_safely'),
    ]

    operations = [
    ]
