# Generated by Django 5.2.6 on 2025-11-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_merge_20251121_2238'),
        ('shop', '0018_merge_20251123_1347'),
    ]

    operations = [
    ]
