# Generated by Django 5.2.6 on 2025-12-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_book_format'),
        ('shop', '0019_merge_20251123_1354'),
    ]

    operations = [
    ]
